# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy static site to Azure Web App - exchangekb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write       # required for OIDC login
      contents: read        # required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # No Node.js build step needed â€“ repo is just static HTML/CSS/JS

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_40A258278B3E4856A73EF47310002A8A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A4879AA0C05F479797512A0FCC7C5BA4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F6F5D8435A904703AAC66DA4C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'exchangekb'
          slot-name: 'Production'
          package: .
